name: Push to other repo(develop)

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - name: Checkout develop code
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache

      - name: Creates output
        run: sh ./build.sh

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.MINJI_SECRET_TOKEN }}
        with:
          source-directory: 'output'
          destination-github-username: 'minji-gwak'
          destination-repository-name: 'gongsilock-frontend'
          user-email: 'mini0006@naver.com'
          user-name: 'minji-gwak'
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: develop
